import { useEffect, useState } from 'react'
import { Check, Copy, Mic, RotateCcw, Trash2 } from '../../shared/ui/SettingsIcons'
import { convertFileSrc } from '@tauri-apps/api/core'
import type { DictationController } from '../../app/useIslandApp'
import type { AppSettings, HistoryEntry } from '../../shared/lib/dictationTypes'
import { DictationModels } from './DictationModels'
import { DictationAdvanced } from './DictationAdvanced'
import { DictationShortcut } from './DictationShortcut'
import { dictationPages, type DictationPage } from './dictationPages'
import { Button, FeatureToggle, Input } from '../../shared/ui/SettingsControls'
import { Select } from '../../shared/ui/Select'
import { CommitInput, DictationField, DictationToggle } from './DictationFields'
import './dictation.css'

export function DictationSettings({ controller: c, page, locale, onEnable, onDisable, onPage }: {
  controller: DictationController; page: DictationPage; locale: 'ru' | 'en'; onEnable: () => Promise<void>; onDisable?: () => Promise<void>; onPage: (page: DictationPage) => void
}) {
  const ru = locale === 'ru'
  const t = (a: string, b: string) => ru ? a : b
  const [channels, setChannels] = useState<number>(0)
  const [key, setKey] = useState('')
  const [providerModels, setProviderModels] = useState<string[]>([])
  const [copied, setCopied] = useState<number | null>(null)
  const [historyAudio, setHistoryAudio] = useState<{ id: number; url: string } | null>(null)
  const { api, data } = c
  const run = (id: string, action: () => Promise<unknown>) => { void c.run(id, action).catch(() => undefined) }
  const microphone = data?.settings.selected_microphone
  const initialized = Boolean(data)
  useEffect(() => {
    if (!initialized || page !== 'general') return
    let active = true
    void api.getMicrophoneChannels(microphone ?? 'default').then((count) => { if (active) setChannels(count) }).catch(() => { if (active) setChannels(0) })
    return () => { active = false }
  }, [api, microphone, initialized, page])
  const error = c.error ? <div className="dictation-error" role="alert"><strong>{t('Не удалось выполнить действие', 'Could not complete the action')}</strong><p>{c.error}</p><Button type="button" onClick={() => run('refresh', () => c.refresh())}>{t('Повторить', 'Retry')}</Button></div> : null
  if (!data) return <div className="dictation-page"><h2 className="settings-page-heading">{t('Диктовка', 'Dictation')}</h2><section className="dictation-welcome"><span className="dictation-welcome__icon"><Mic size={30} /></span><h3>{t('Говорите — текст появится там, где курсор', 'Speak where you type')}</h3><p>{t('Распознавание работает на компьютере. Выберите модель, сочетание клавиш и попробуйте короткую запись.', 'Speech is recognized on your computer. Choose a model and a shortcut, then try a short recording.')}</p><Button type="button" variant="primary" disabled={Boolean(c.busy)} onClick={() => { void onEnable().then(() => onPage('models')).catch(() => undefined) }}>{c.busy ? t('Подготовка…', 'Preparing…') : t('Настроить диктовку', 'Set up dictation')}</Button><small>{t('На этом шаге модели не скачиваются.', 'No models are downloaded at this step.')}</small></section>{error}</div>
  const s = data.settings
  const model = data.models.find((item) => item.id === s.selected_model)
  const recording = data.status?.phase === 'recording' || data.status?.phase === 'streaming'
  const selectedProvider = s.post_process_providers?.find((item) => item.id === s.post_process_provider_id)
  const selectedPrompt = s.post_process_prompts?.find((item) => item.id === s.post_process_selected_prompt_id)
  const toggle = (label: string, field: keyof AppSettings, action: (checked: boolean) => Promise<unknown>, hint?: string) => <DictationToggle label={label} checked={Boolean(s[field])} hint={hint} onChange={(checked) => run(String(field), () => action(checked))} />
  const select = (label: string, value: string | number, options: [string, string][], action: (value: string) => Promise<unknown>, hint?: string) => <DictationField label={label} hint={hint}><Select ariaLabel={label} value={String(value)} onChange={(next) => run(label, () => action(next))} options={options.map(([value, label]) => ({ value, label }))} /></DictationField>
  return <div className="dictation-page" aria-busy={Boolean(c.busy)}>
    {page !== 'models' ? <h2 className="settings-page-heading">{dictationPages[page][ru ? 0 : 1]}</h2> : null}
    {error}
    {page === 'general' ? <>
      <FeatureToggle icon={<Mic size={24} weight={c.enabled ? 'fill' : 'regular'} />} label={t('Диктовка', 'Dictation')} checked={c.enabled} disabled={Boolean(c.busy)} hint={c.enabled ? t('Готова к записи по сочетанию клавиш.', 'Ready to record with your shortcut.') : t('Микрофон выключен, модель выгружена.', 'Microphone is off. The model is unloaded.')} onChange={(enabled) => { void (enabled ? onEnable() : onDisable?.())?.catch(() => {}) }} />
      <section className="dictation-card"><DictationField label={t('Модель', 'Model')} hint={model?.name ?? t('Сначала выберите и скачайте модель.', 'Choose and download a model first.')}><Button type="button" onClick={() => onPage('models')}>{t('Выбрать', 'Choose')}</Button></DictationField>
        {select(t('Микрофон', 'Microphone'), s.selected_microphone ?? 'default', [['default', t('Системный', 'System default')], ...data.microphones.map((device): [string, string] => [device.name, device.name])], api.setSelectedMicrophone, t('Выберите исходный микрофон. Виртуальный вход Better Voice можно выбрать отдельно.', 'Choose your original microphone. You can select the Better Voice virtual input explicitly.'))}
        {channels > 1 ? select(t('Канал', 'Channel'), s.selected_channel ?? 'all', [['all', t('Все каналы', 'All channels')], ...Array.from({ length: channels }, (_, index): [string, string] => [String(index), String(index + 1)])], (value) => api.setSelectedChannel(value === 'all' ? null : Number(value))) : null}
        {select(t('Режим сочетания', 'Shortcut mode'), s.shortcut_activation ?? 'toggle', [['toggle', t('Нажать, чтобы начать и закончить', 'Press to start and stop')], ['push_to_talk', t('Удерживать во время записи', 'Hold while recording')], ['hold_or_toggle', t('Удержание или переключение', 'Hold or toggle')]], (value) => api.changeShortcutActivationSetting(value as NonNullable<AppSettings['shortcut_activation']>))}
        <DictationField label={t('Сочетание клавиш', 'Keyboard shortcut')} hint={t('Например: Ctrl+Space. Escape отменяет запись.', 'For example: Ctrl+Space. Escape cancels a recording.')}><DictationShortcut controller={c} id="transcribe" locale={locale} /></DictationField>
        <DictationField label={t('Отмена записи', 'Cancel recording')}><DictationShortcut controller={c} id="cancel" locale={locale} /></DictationField>
        {model?.supports_language_selection ? select(t('Язык речи', 'Speech language'), s.selected_language ?? 'auto', [...(model.supports_language_detection ? [['auto', t('Определять', 'Detect')] as [string, string]] : []), ...model.supported_languages.map((language): [string, string] => [language, new Intl.DisplayNames([locale], { type: 'language' }).of(language) ?? language])], api.changeSelectedLanguageSetting) : null}
        {model?.supports_translation ? toggle(t('Переводить на английский', 'Translate to English'), 'translate_to_english', api.changeTranslateToEnglishSetting) : null}
      </section>
      <section className="dictation-card"><h3>{t('Короткая проба', 'Try a short recording')}</h3><p>{t('Откройте текстовое поле в любом приложении и нажмите сочетание. Результат также останется в истории.', 'Open a text field in any app and press the shortcut. The result will also be available in History.')}</p><Button type="button" variant="primary" disabled={!c.enabled || !model?.is_downloaded} onClick={() => run('try', () => api.toggle())}><Mic size={16} />{recording ? t('Закончить запись', 'Stop recording') : t('Начать запись', 'Start recording')}</Button><Button type="button" disabled={!c.enabled || !recording} onClick={() => run('cancel', () => api.cancelOperation())}>{t('Отменить запись', 'Cancel recording')}</Button></section>
    </> : null}
    {page === 'models' ? <DictationModels controller={c} locale={locale} /> : null}
    {page === 'history' ? <>
      <section className="dictation-card">{select(t('Хранить записи', 'Keep recordings'), s.recording_retention_period ?? 'preserve_limit', [['never', t('Без срока', 'Keep indefinitely')], ['preserve_limit', t('В пределах истории', 'Within history limit')], ['days3', t('3 дня', '3 days')], ['weeks2', t('2 недели', '2 weeks')], ['months3', t('3 месяца', '3 months')]], (value) => api.updateRecordingRetentionPeriod(({ days3: 'days3', weeks2: 'weeks2', months3: 'months3' }[value] ?? value)))}<DictationField label={t('Размер истории', 'History limit')}><CommitInput type="number" value={String(s.history_limit ?? 5)} onSave={(value) => run('history-limit', () => api.updateHistoryLimit(Math.max(1, Math.min(10000, Number(value)))))} /></DictationField></section>
      {data.history.length ? data.history.map((entry: HistoryEntry) => <article className="dictation-history" key={entry.id}><time dateTime={new Date(entry.timestamp * 1000).toISOString()}>{new Date(entry.timestamp * 1000).toLocaleString(locale)}</time><p>{entry.post_processed_text ?? entry.transcription_text}</p><div className="dictation-history__actions"><Button type="button" onClick={() => { void navigator.clipboard.writeText(entry.post_processed_text ?? entry.transcription_text).then(() => setCopied(entry.id)) }}>{copied === entry.id ? <Check size={15} /> : <Copy size={15} />}{t('Копировать', 'Copy')}</Button><Button type="button" disabled={!c.enabled} onClick={() => run(`retry:${entry.id}`, () => api.retryHistoryEntryTranscription(entry.id))}><RotateCcw size={15} />{t('Распознать снова', 'Transcribe again')}</Button><Button type="button" onClick={() => run('play-audio', async () => setHistoryAudio({ id: entry.id, url: convertFileSrc(await api.getAudioFilePath(entry.file_name)) }))}>{t('Аудио', 'Audio')}</Button><Button type="button" aria-pressed={entry.saved} onClick={() => run('save-history', () => api.toggleHistoryEntrySaved(entry.id))}>{entry.saved ? t('Сохранена', 'Saved') : t('Сохранить', 'Keep')}</Button><Button type="button" aria-label={t('Удалить запись', 'Delete entry')} onClick={() => run('delete-history', () => api.deleteHistoryEntry(entry.id))}><Trash2 size={15} /></Button></div>{historyAudio?.id === entry.id ? <audio controls src={historyAudio.url} /> : null}</article>) : <div className="dictation-empty"><Mic size={28} /><h3>{t('Здесь появятся ваши записи', 'Your recordings appear here')}</h3><p>{t('Начните диктовку сочетанием клавиш.', 'Start dictating with your keyboard shortcut.')}</p></div>}
    </> : null}
    {page === 'history' && data.hasMoreHistory ? <Button type="button" onClick={() => run('more-history', c.loadMoreHistory)}>{t('Показать ещё', 'Load more')}</Button> : null}
    {page === 'dictionary' ? <section className="dictation-card"><h3>{t('Слова, которые важно узнавать', 'Words to recognize')}</h3><p>{t('Имена, термины и названия. Каждое слово или фраза — с новой строки.', 'Names, terms and titles. One word or phrase per line.')}</p><CommitInput multiline value={(s.custom_words ?? []).join('\n')} onSave={(value) => run('dictionary', () => api.updateCustomWords(value.split('\n').map((word) => word.trim()).filter(Boolean)))} />{toggle(t('Убирать слова-паразиты', 'Remove filler words'), 'filler_word_removal_enabled', api.changeFillerWordRemovalEnabledSetting, t('Убирает «э-э», «а-а», «эм» и похожие паузы. Обычные слова и одиночные союзы сохраняются.', 'Removes hesitation sounds such as “э-э”, “а-а” and “эм”. Keeps ordinary words and single conjunctions.'))}<p>{t('Свои слова-паразиты, по одному на строку. Пустое поле возвращает стандартный список.', 'Custom filler words, one per line. Leave empty to use the default list.')}</p><CommitInput multiline value={(s.custom_filler_words ?? []).join('\n')} onSave={(value) => run('fillers', () => api.updateCustomFillerWords(value.split('\n').map((word) => word.trim()).filter(Boolean)))} /><DictationField label={t('Порог коррекции', 'Correction threshold')}><Input type="range" min={0} max={1} step={.05} defaultValue={s.word_correction_threshold ?? .8} aria-label={t('Порог коррекции', 'Correction threshold')} onChange={(event) => { const value = Number(event.target.value); run('correction', () => api.changeWordCorrectionThresholdSetting(value)) }} /></DictationField></section> : null}
    {page === 'processing' ? <>
      <section className="dictation-card">{toggle(t('Обработка с ИИ', 'AI processing'), 'post_process_enabled', api.changePostProcessEnabledSetting, t('Запустите диктовку сочетанием для ИИ: распознанный текст отправится выбранному сервису, а его ответ вставится в активное приложение. Обычная диктовка остаётся локальной.', 'Use the AI shortcut: recognized text is sent to your chosen service, then its response is pasted into the active app. Regular dictation stays local.'))}
        {select(t('Провайдер', 'Provider'), s.post_process_provider_id ?? '', (s.post_process_providers ?? []).filter((provider) => provider.id !== 'apple_intelligence').map((provider) => [provider.id, provider.label]), api.setPostProcessProvider)}
        {selectedProvider ? <><DictationField label="Endpoint"><CommitInput type="url" value={selectedProvider.base_url} onSave={(value) => run('endpoint', () => api.changePostProcessBaseUrlSetting(selectedProvider.id, value))} /></DictationField><DictationField label={t('Ключ API', 'API key')} hint={t('Хранится с защитой Windows. Сохранённый ключ не отображается.', 'Protected by Windows. Saved keys are never displayed.')}><form className="dictation-input-action" onSubmit={(event) => { event.preventDefault(); run('key', async () => { await api.changePostProcessApiKeySetting(selectedProvider.id, key); setKey('') }) }}><Input type="password" value={key} autoComplete="off" aria-label={t('Ключ API', 'API key')} onChange={(event) => setKey(event.target.value)} /><Button type="submit">{t('Сохранить', 'Save')}</Button></form></DictationField><DictationField label={t('Модель ИИ', 'AI model')}><CommitInput value={s.post_process_models?.[selectedProvider.id] ?? ''} onSave={(value) => run('processing-model', () => api.changePostProcessModelSetting(selectedProvider.id, value))} /></DictationField><Button type="button" onClick={() => run('provider-models', async () => setProviderModels(await api.fetchPostProcessModels(selectedProvider.id)))}>{t('Получить список моделей', 'Fetch available models')}</Button>{providerModels.length ? select(t('Доступные модели', 'Available models'), s.post_process_models?.[selectedProvider.id] ?? '', providerModels.map((name) => [name, name]), (value) => api.changePostProcessModelSetting(selectedProvider.id, value)) : null}</> : null}
      </section>
      <section className="dictation-card"><h3>{t('Шаблон', 'Prompt')}</h3><p>{t('Вставьте ${output} там, где нужен распознанный текст.', 'Insert ${output} where the recognized text belongs.')}</p>{select(t('Выбрать шаблон', 'Choose prompt'), s.post_process_selected_prompt_id ?? '', (s.post_process_prompts ?? []).map((prompt) => [prompt.id, prompt.name]), api.setPostProcessSelectedPrompt)}{selectedPrompt ? <><CommitInput value={selectedPrompt.name} onSave={(name) => run('prompt-name', () => api.updatePostProcessPrompt(selectedPrompt.id, name, selectedPrompt.prompt))} /><CommitInput multiline value={selectedPrompt.prompt} onSave={(prompt) => run('prompt', () => api.updatePostProcessPrompt(selectedPrompt.id, selectedPrompt.name, prompt))} /><Button type="button" onClick={() => run('delete-prompt', () => api.deletePostProcessPrompt(selectedPrompt.id))}>{t('Удалить шаблон', 'Delete prompt')}</Button></> : null}<Button type="button" onClick={() => run('add-prompt', () => api.addPostProcessPrompt(t('Новый шаблон', 'New prompt'), '${output}'))}>{t('Добавить шаблон', 'Add prompt')}</Button><DictationField label={t('Диктовка с ИИ', 'Dictate with AI')}><DictationShortcut controller={c} id="transcribe_with_post_process" locale={locale} /></DictationField></section>
    </> : null}
    {page === 'advanced' ? <>
      <DictationAdvanced controller={c} locale={locale} />
      <section className="dictation-card"><h3>{t('Запись', 'Recording')}</h3>{toggle(t('Определять речь', 'Detect speech'), 'vad_enabled', api.changeVadEnabledSetting)}{toggle(t('Звуки начала и конца', 'Start and stop sounds'), 'audio_feedback', api.changeAudioFeedbackSetting)}{toggle(t('Приглушать звук при записи', 'Mute playback while recording'), 'mute_while_recording', api.changeMuteWhileRecordingSetting)}{toggle(t('Держать микрофон открытым', 'Keep microphone open'), 'always_on_microphone', api.updateMicrophoneMode, t('По умолчанию микрофон работает только во время записи.', 'By default, the microphone is opened only while recording.'))}{select(t('Выгружать модель через', 'Unload model after'), s.model_unload_timeout ?? 'min5', [['immediately', t('Сразу', 'Immediately')], ['min2', t('2 минуты', '2 minutes')], ['min5', t('5 минут', '5 minutes')], ['min10', t('10 минут', '10 minutes')], ['min15', t('15 минут', '15 minutes')], ['hour1', t('1 час', '1 hour')], ['never', t('Не выгружать', 'Never')]], (value) => api.setModelUnloadTimeout(value as NonNullable<AppSettings['model_unload_timeout']>))}</section>
      <section className="dictation-card"><h3>{t('Вставка текста', 'Text insertion')}</h3>{select(t('Способ вставки', 'Paste method'), s.paste_method ?? 'ctrl_v', [['ctrl_v', 'Ctrl+V'], ['shift_insert', 'Shift+Insert'], ['ctrl_shift_v', 'Ctrl+Shift+V'], ['direct', t('Набор текста', 'Type text')], ['none', t('Только история', 'History only')], ['external_script', t('Внешняя программа', 'External program')]], api.changePasteMethodSetting)}{s.paste_method === 'external_script' ? <DictationField label={t('Путь к программе', 'Program path')} hint={t('Получает распознанный текст аргументом. Выберите свою программу для вставки.', 'Receives recognized text as an argument. Choose your own program to paste it.')}><CommitInput value={s.external_script_path ?? ''} onSave={(path) => run('external-script', () => api.changeExternalScriptPathSetting(path || null))} /></DictationField> : null}{select(t('Буфер обмена', 'Clipboard'), s.clipboard_handling ?? 'dont_modify', [['dont_modify', t('Восстанавливать', 'Restore')], ['copy_to_clipboard', t('Оставлять результат', 'Keep result')]], api.changeClipboardHandlingSetting)}{toggle(t('Пробел после текста', 'Trailing space'), 'append_trailing_space', api.changeAppendTrailingSpaceSetting)}{toggle(t('Отправлять после вставки', 'Submit after pasting'), 'auto_submit', api.changeAutoSubmitSetting, t('Нажимает Enter в целевом приложении.', 'Presses Enter in the target app.'))}</section>
      <section className="dictation-card"><h3>{t('Диагностика', 'Diagnostics')}</h3>{toggle(t('Экспериментальные функции', 'Experimental features'), 'experimental_enabled', api.changeExperimentalEnabledSetting)}{s.experimental_enabled ? toggle(t('Восстанавливать буфер после чтения · бета', 'Restore clipboard after read · beta'), 'reliable_paste', api.changeReliablePasteSetting) : null}<Button type="button" onClick={() => run('mic-privacy', () => api.openMicrophonePrivacySettings())}>{t('Доступ к микрофону в Windows', 'Windows microphone access')}</Button><Button type="button" disabled={!data.modelStatus?.is_loaded} onClick={() => run('unload', () => api.unloadModelManually())}>{t('Выгрузить модель сейчас', 'Unload model now')}</Button></section>
    </> : null}

  </div>
}
