// Fixed data from the pinned Handy catalog; no network requests.
import type { AppSettings, ModelInfo } from '../shared/lib/dictationTypes'
export const dictationSettings: AppSettings = {
  "selected_model": "handy-computer/whisper-small-gguf/whisper-small-Q8_0.gguf",
  "bindings": {
    "transcribe": {
      "id": "transcribe",
      "name": "Transcribe",
      "description": "",
      "default_binding": "Ctrl+Space",
      "current_binding": "Ctrl+Space"
    }
  },
  "shortcut_activation": "toggle",
  "hold_threshold_ms": 250,
  "selected_language": "auto",
  "model_unload_timeout": "min5",
  "vad_enabled": true,
  "vad_backend": "silero",
  "audio_feedback": true,
  "audio_feedback_volume": 0.5,
  "sound_theme": "marimba",
  "always_on_microphone": false,
  "post_process_enabled": false,
  "custom_words": [
    "Music Island",
    "Better Voice"
  ],
  "word_correction_threshold": 0.18,
  "history_limit": 50,
  "recording_retention_period": "preserve_limit",
  "paste_method": "ctrl_v",
  "clipboard_handling": "dont_modify"
}
export const dictationModels: ModelInfo[] = [
  {
    "id": "handy-computer/whisper-small-gguf/whisper-small-Q8_0.gguf",
    "name": "Whisper Small",
    "description": "99-language speech-to-text with translation, auto language detection, segment-level timestamps.",
    "filename": "whisper-small-Q8_0.gguf",
    "source": {
      "HuggingFace": {
        "repo_id": "handy-computer/whisper-small-gguf",
        "revision": "c0214bd34be9296695486f838e0142f900803159"
      }
    },
    "size_mb": 257,
    "is_downloaded": true,
    "is_downloading": false,
    "partial_size": 0,
    "is_directory": false,
    "engine_type": "TranscribeCpp",
    "accuracy_score": 80,
    "speed_score": 78,
    "supports_translation": true,
    "is_recommended": false,
    "supported_languages": [
      "en",
      "zh",
      "de",
      "es",
      "ru",
      "ko",
      "fr",
      "ja",
      "pt",
      "tr",
      "pl",
      "ca",
      "nl",
      "ar",
      "sv",
      "it",
      "id",
      "hi",
      "fi",
      "vi",
      "he",
      "uk",
      "el",
      "ms",
      "cs",
      "ro",
      "da",
      "hu",
      "ta",
      "no",
      "th",
      "ur",
      "hr",
      "bg",
      "lt",
      "la",
      "mi",
      "ml",
      "cy",
      "sk",
      "te",
      "fa",
      "lv",
      "bn",
      "sr",
      "az",
      "sl",
      "kn",
      "et",
      "mk",
      "br",
      "eu",
      "is",
      "hy",
      "ne",
      "mn",
      "bs",
      "kk",
      "sq",
      "sw",
      "gl",
      "mr",
      "pa",
      "si",
      "km",
      "sn",
      "yo",
      "so",
      "af",
      "oc",
      "ka",
      "be",
      "tg",
      "sd",
      "gu",
      "am",
      "yi",
      "lo",
      "uz",
      "fo",
      "ht",
      "ps",
      "tk",
      "nn",
      "mt",
      "sa",
      "lb",
      "my",
      "bo",
      "tl",
      "mg",
      "as",
      "tt",
      "haw",
      "ln",
      "ha",
      "ba",
      "jw",
      "su"
    ],
    "supports_language_selection": true,
    "is_custom": false,
    "supports_streaming": false,
    "supports_language_detection": true
  },
  {
    "id": "handy-computer/whisper-large-v3-turbo-gguf/whisper-large-v3-turbo-Q8_0.gguf",
    "name": "Whisper Large v3 Turbo",
    "description": "100-language speech-to-text with auto language detection, segment-level timestamps.",
    "filename": "whisper-large-v3-turbo-Q8_0.gguf",
    "source": {
      "HuggingFace": {
        "repo_id": "handy-computer/whisper-large-v3-turbo-gguf",
        "revision": "5eaf945c7978e564bae5b28a5b1639dd93c2bfb1"
      }
    },
    "size_mb": 845,
    "is_downloaded": false,
    "is_downloading": false,
    "partial_size": 0,
    "is_directory": false,
    "engine_type": "TranscribeCpp",
    "accuracy_score": 88,
    "speed_score": 35,
    "supports_translation": false,
    "is_recommended": false,
    "supported_languages": [
      "en",
      "zh",
      "de",
      "es",
      "ru",
      "ko",
      "fr",
      "ja",
      "pt",
      "tr",
      "pl",
      "ca",
      "nl",
      "ar",
      "sv",
      "it",
      "id",
      "hi",
      "fi",
      "vi",
      "he",
      "uk",
      "el",
      "ms",
      "cs",
      "ro",
      "da",
      "hu",
      "ta",
      "no",
      "th",
      "ur",
      "hr",
      "bg",
      "lt",
      "la",
      "mi",
      "ml",
      "cy",
      "sk",
      "te",
      "fa",
      "lv",
      "bn",
      "sr",
      "az",
      "sl",
      "kn",
      "et",
      "mk",
      "br",
      "eu",
      "is",
      "hy",
      "ne",
      "mn",
      "bs",
      "kk",
      "sq",
      "sw",
      "gl",
      "mr",
      "pa",
      "si",
      "km",
      "sn",
      "yo",
      "so",
      "af",
      "oc",
      "ka",
      "be",
      "tg",
      "sd",
      "gu",
      "am",
      "yi",
      "lo",
      "uz",
      "fo",
      "ht",
      "ps",
      "tk",
      "nn",
      "mt",
      "sa",
      "lb",
      "my",
      "bo",
      "tl",
      "mg",
      "as",
      "tt",
      "haw",
      "ln",
      "ha",
      "ba",
      "jw",
      "su",
      "yue"
    ],
    "supports_language_selection": true,
    "is_custom": false,
    "supports_streaming": false,
    "supports_language_detection": true
  },
  {
    "id": "handy-computer/gigaam-v3-ctc-gguf/gigaam-v3-ctc-Q8_0.gguf",
    "name": "GigaAM v3 CTC",
    "description": "Russian speech-to-text with token-level timestamps.",
    "filename": "gigaam-v3-ctc-Q8_0.gguf",
    "source": {
      "HuggingFace": {
        "repo_id": "handy-computer/gigaam-v3-ctc-gguf",
        "revision": "c3c611444004820c21c3b68312a41c83c1e4813b"
      }
    },
    "size_mb": 259,
    "is_downloaded": false,
    "is_downloading": false,
    "partial_size": 0,
    "is_directory": false,
    "engine_type": "TranscribeCpp",
    "accuracy_score": 57,
    "speed_score": 98,
    "supports_translation": false,
    "is_recommended": false,
    "supported_languages": [
      "ru"
    ],
    "supports_language_selection": true,
    "is_custom": false,
    "supports_streaming": false,
    "supports_language_detection": false
  }
]

export const gigaamRnnt: ModelInfo = {
  "id": "handy-computer/gigaam-v3-e2e-rnnt-gguf/gigaam-v3-e2e-rnnt-Q8_0.gguf",
  "name": "GigaAM v3 E2E-RNN-T",
  "description": "Russian speech-to-text with token-level timestamps.",
  "filename": "gigaam-v3-e2e-rnnt-Q8_0.gguf",
  "source": {
    "HuggingFace": {
      "repo_id": "handy-computer/gigaam-v3-e2e-rnnt-gguf",
      "revision": "f719d70812344f4d0fb8c11c0887b190501a7465"
    }
  },
  "size_mb": 261,
  "is_downloaded": false,
  "is_downloading": false,
  "partial_size": 0,
  "is_directory": false,
  "engine_type": "TranscribeCpp",
  "accuracy_score": 70,
  "speed_score": 94,
  "supports_translation": false,
  "is_recommended": false,
  "supported_languages": [
    "ru"
  ],
  "supports_language_selection": false,
  "is_custom": false,
  "supports_streaming": false,
  "supports_language_detection": false
}

export const parakeetEnglish: ModelInfo = {
  "id": "handy-computer/parakeet-unified-en-0.6b-gguf/parakeet-unified-en-0.6b-Q8_0.gguf",
  "name": "Parakeet Unified EN 0.6B",
  "description": "Fast, accurate live English transcription",
  "filename": "parakeet-unified-en-0.6b-Q8_0.gguf",
  "source": {
    "HuggingFace": {
      "repo_id": "handy-computer/parakeet-unified-en-0.6b-gguf",
      "revision": "7e948f21b7bdbac698d3318db9d350f1096f3b6c"
    }
  },
  "size_mb": 697,
  "is_downloaded": false,
  "is_downloading": false,
  "partial_size": 0,
  "is_directory": false,
  "engine_type": "TranscribeCpp",
  "accuracy_score": 90,
  "speed_score": 79,
  "supports_translation": false,
  "is_recommended": true,
  "supported_languages": [
    "en"
  ],
  "supports_language_selection": false,
  "is_custom": false,
  "supports_streaming": true,
  "supports_language_detection": false
}
